#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/config/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/nginx-vhosts/functions"

APP="$1"

eval "$(config_export app "$APP")"

CONFIG_FOLDER="$DOKKU_ROOT/$APP/nginx.conf.d"

CONFIG_FILE="$CONFIG_FOLDER/client-max-body-size.conf"

[[ -d "$CONFIG_FOLDER" ]] || mkdir "$CONFIG_FOLDER"

echo "-----> Setting client-max-body-size"
echo "Writing to $CONFIG_FILE"
echo "# auotgen by client-max-body-size plugin" > $CONFIG_FILE

GLOBAL_VAL=$(config_get "--global" client_max_body_size) || true
LOCAL_VAL=$(config_get "$APP" client_max_body_size) || true

echo "Global: ${GLOBAL_VAL}, Local: ${LOCAL_VAL}"

if [ ! -z "$LOCAL_VAL" ]; then
  echo "client_max_body_size $LOCAL_VAL;" >> $CONFIG_FILE
elif [ ! -z "$GLOBAL_VAL" ]; then
  echo "client_max_body_size $GLOBAL_VAL;" >> $CONFIG_FILE
fi

chown dokku:dokku $CONFIG_FILE

restart_nginx
